[package]
name = "patchShebangsRust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
walkdir = "2.5"
regex = "1.10"
anyhow = "1.0"
filetime = "0.2.26"
